### ISSUE TITLE
Exception in Curiosity.SFTP.SSH.Net

### ISSUE THREAD

**Issue by DevCorvette** [siisltd/Curiosity.Utils#51]
When I called `sftpClient.UploadFileToServerAsync()` and file is already exist. I had an Exception:
```
System.Resources.MissingManifestResourceException: Could not find the resource "Curiosity.SFTP.SSH.Net.Resources.LNG.resources" among the resources "Curiosity.SFTP.SSH.Net.LNG.resources" embedded in the assembly "Curiosity.SFTP.SSH.Net", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.Resources.ResourceManager.GetString(String name)
   at Curiosity.SFTP.SSH.Net.LNG.GetString(String name, String[] formatterNames)
   at Curiosity.SFTP.SSH.Net.LNG.get_SftpClient_SameFileAlreadyExists()
   at Curiosity.SFTP.SSH.Net.SftpClient.<>c__DisplayClass12_0.<UploadFileToServerAsync>b__0()
   at Polly.AsyncPolicy.<>c__DisplayClass4_0.<ExecuteAsync>b__0(Context _, CancellationToken _)
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ExternalDataExportTool.Core.DataExporter.ExportAsync(ProjectFilterType filter, DateTimePeriod period, CancellationToken cancellationToken) in C:\Projects\SIIS\external-data-export-tool\src\ExternalDataExportTool\Core\DataExporter.cs:line 117
   at Curiosity.Hosting.CuriosityToolAppBootstrapper`2.RunInternalAsync(String[] rawArguments, TArgs arguments, TConfiguration configuration, IConfigurationProvider`1 configurationProvider, String customContentRootDirectory, CancellationToken cancellationToken)
   at Curiosity.Hosting.CuriosityAppBootstrapper`2.RunAsync(String[] args, CancellationToken cancellationToken)
```

**Comment by Markeli** [comment]
Fixed at `1.4.1`.
